### ISSUE TITLE
Contao 4.13 compatibility

### ISSUE THREAD

**Issue by Nightwing0815** [cliffparnitzky/TinyMcePluginLoader#16]
Hi cliff,

on contao 4.10.6, there's a problem with the plugin loader, the following error occurs. I don't use a custom template of tinymce.

`Uncaught SyntaxError: "" string literal contains an unescaped line break`
`plugins: "autosave charmap code fullscreen image importcss link lists paste searchreplace stripnbsp tabfocus table visualblocks visualchars',`

My installed addons from you:

-         "cliffparnitzky/tiny-mce-code-mirror": "^1.1",
-         "cliffparnitzky/tiny-mce-colorpicker": "^1.1",
-         "cliffparnitzky/tiny-mce-context-menu": "^2.1",
-         "cliffparnitzky/tiny-mce-horizontal-ruler": "^1.1",
-         "cliffparnitzky/tiny-mce-image-enhancement": "^1.0",
-         "cliffparnitzky/tiny-mce-insert-date-time": "^2.1",
-         "cliffparnitzky/tiny-mce-link-auto-detect": "^2.1",
-         "cliffparnitzky/tiny-mce-link-lightbox": "^1.0",
-         "cliffparnitzky/tiny-mce-pagebreak": "^2.1",
-         "cliffparnitzky/tiny-mce-plugin-loader": "^2.1",
-         "cliffparnitzky/tiny-mce-strikethrough": "^2.0",
-         "cliffparnitzky/tiny-mce-text-color": "^1.1",
-         "cliffparnitzky/tiny-mce-underline": "^1.0",
-         "cliffparnitzky/tiny-mce-word-count": "^2.1",

and here's the script with the error, from the DOM (firefox, F12):

`<script>
window.tinymce && tinymce.init({
  selector: '#ctrl_text',
  min_height: 336,
  language: 'de',
  element_format: 'html',
  document_base_url: '',
  entities: '160,nbsp,60,lt,62,gt,173,shy',
  branding: false,
  setup: function(editor) {
    editor.getElement().removeAttribute('required');
  },
  init_instance_callback: function(editor) {
    if (document.activeElement && document.activeElement.id && document.activeElement.id == editor.id) {
      editor.editorManager.get(editor.id).focus();
    }
    editor.on('focus', function() { Backend.getScrollOffset(); });
  },

  file_picker_callback: function (callback, value, meta) {
      Backend.openModalSelector({
        'id': 'tl_listing',
        'title': document.getElement('.tox-dialog__title').get('text'),
        'url': Contao.routes.backend_picker + '?context=' + (meta.filetype == 'file' ? 'link' : 'file') + '&extras[fieldType]=radio&extras[filesOnly]=true&extras[source]=tl_content.1013&value=' + value + '&popup=1',
        'callback': function(table, val) {
          callback(val.join(','));
        }
      });
    },
  file_picker_types: ["image","file"],
  
  content_css: 'system/themes/flexible/tinymce.min.css',
  
 plugins: "autosave charmap code fullscreen image importcss link lists paste searchreplace stripnbsp tabfocus table visualblocks visualchars',
 colorpicker codemirror contextmenu hr insertdatetime textcolor autolink wordcount pagebreak",
  extended_valid_elements: 'q[cite|class|title],article,section,hgroup,figure,figcaption',
  
  menubar: 'file edit insert view format table',
  
  browser_spellcheck: true,
  tabfocus_elements: ':prev,:next',
  importcss_append: true,
  toolbar1: 'link unlink | image | formatselect | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | code',
  
    
  toolbar2: " hr | insertdatetime | forecolor backcolor | pagebreak |",
  codemirror: {
  indentOnInit: false,    // Whether or not to indent code on init. 
  path: 'codemirror-5.2', // Path to CodeMirror distribution
  config: {               // CodeMirror config object
     mode: 'htmlmixed',
     lineNumbers: true,
     foldGutter: true
  }
},
  rel_list:   [
    {title: "None", value: ""},
    {title: "Lightbox Element", value: "lightbox"},
    {title: "Lightbox Galerie", value: "lightbox[multi]"}
  ],
  insertdatetime_formats: ["%d.%m.%Y", "%H:%M"],
  image_advtab: true,
  image_title: true,
  pagebreak_separator: "<img data-mce-src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-mce-resize="false" alt="" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" class="mce-pagebreak" data-mce-selected="1" style="page-break-after: always; height: 0px;">",
});
</script>
`

Thanks in advance!

Best regards,

ToM

**Comment by cliffparnitzky** [comment]
Thx. Yes, I can confirm. There seems to be a problem with manipulating the tiny configuration.

**Comment by Nightwing0815** [comment]
Hi,

here's a quick'n'dirty workaround, to get at least some parts working:

install the plugins mentioned above in a contao 4.9.xx installation, go to backend and edit some text, where the tinymce is loaded.
Now have a look in site's sourcecode, where you'll find the script part from be_tineMC.html5 template:
In my case, i had to remove some items on the plugin row and correct above mentioned rowbreak.
Have a look in browser's console (you'll find that in browser's web dev menu), it's telling you, which one create's an error, put it out of the string and reload ;-)

ToM

**Comment by Nightwing0815** [comment]
Hi Cliff,

think I found the solution: < should be escaped, too: \<
Have a look in TinyMcePluginLoader.php, line 44 (first is missing, second is maybe wrong):
`private static $TINY_LOADER_REGEX = "\<script>(\n|\r\n)+window.tinymce && tinymce.init\(\{.*\}\);(\n|\r\n)+\</script>/Us";`
Now your addons are working, at least the one's without JS, therefore you should update path and some variables:
`codemirror Error: editor.addButton has been removed in tinymce 5x, use editor.ui.registry.addButton or editor.ui.registry.addToggleButton or editor.ui.registry.addSplitButton instead`

ToM

**Comment by cliffparnitzky** [comment]
Compatibility is ready. First plugins are already usable: https://github.com/cliffparnitzky/TinyMcePluginLoader#plugins
