### ISSUE TITLE
Plugin wishes

### ISSUE THREAD

**Issue by cliffparnitzky** [cliffparnitzky/TinyMcePluginLoader#3]
Add a comment for special plugin wishes.

**Comment by cliffparnitzky** [comment]
A better HTML Editor would be fine. Possible plugins:

- https://github.com/aguvillalba/improvedcode
- http://www.avoid.org/codemirror-for-tinymce4

**Comment by felixpfeiffer** [comment]
Hi Cliff,

I just thought about, if ther's a way to add an character counter, that counts just the visible characters, no html-code.
Maybe you have an idea how to do that.

Felix

**Comment by cliffparnitzky** [comment]
@felixpfeiffer I dont know a plugin for character count. Maybe reusing and rewrting the [TinyMceWordCount](https://github.com/cliffparnitzky/TinyMceWordCount) is an option.

**Comment by cliffparnitzky** [comment]
This seems to be new: https://www.tinymce.com/docs/plugins/autosave/

**Comment by cliffparnitzky** [comment]
- [ ] Nice idea: https://github.com/julenpardo/tinymce-table-of-contents
- [ ] Replacement for local storage plugin ???: https://github.com/valtlfelipe/TinyMCE-LocalAutoSave
- [ ] Table of content: https://github.com/tinymce/tinymce/tree/master/src/plugins/toc

**Comment by cliffparnitzky** [comment]
Since 3 years no wish implemented. Not longer needed.
