### ISSUE TITLE
Empty page

### ISSUE THREAD

**Issue by jenda77** [cliffparnitzky/TinyMcePluginLoader#5]
Hello, I have installed your extension but, unfortunately, the TinyMCE editor disappeared. What am I doing wrong?
![snimek obrazovky 2015-04-30 v 22 32 13](https://cloud.githubusercontent.com/assets/3715050/7421932/fd272cf0-ef88-11e4-88ca-2fae6cd1b388.png)

**Comment by cliffparnitzky** [comment]
I need some more infos:
- Which version of plugin loader is installed?
- Which Contao version is used?
- Which plugins, bundles or setups are installed?

**Comment by jenda77** [comment]
Contao 3.4.4. The latest version of your extension, FontAwesome - all manual added

**Comment by cliffparnitzky** [comment]
Hmm, hard to analyse. Any chance to get access to the system (send via mail to contao@cliff-parnitzky.de)

**Comment by jenda77** [comment]
Vielen Dank. Ich schicke dir das gleich.

**Comment by cliffparnitzky** [comment]
Probleme is solved. Never forget the assets folder when installing maually:

![Uploading screenshot.jpg…]()

**Comment by jenda77** [comment]
Bei mir wird nichts weiter gezeigt…

**Comment by jenda77** [comment]
Alles klar. Sorry.
