### ISSUE TITLE
Problems with Rocksolid Custom Elements

### ISSUE THREAD

**Issue by cliffparnitzky** [cliffparnitzky/TinyMcePluginLoader#6]
Using TinyMcePluginLoader and Rocksolid Custom Elements in one installation makes problemes.

This issue has to be tested.

Link to Rocksolid Issue Tracker: http://help.rocksolidthemes.com/discussions/contao/8977-verwendung-kompatibilitt-mit-tinymcepluginloader

**Comment by cliffparnitzky** [comment]
Probleme mentioned by @jenda77 and @ainschy

**Comment by cliffparnitzky** [comment]
So, in einer Test Environment hab ich das mal ausprobiert. Leider gibt es keinen einfachen JS Fehler oder was ähnliches.

Auf Seiten der Rocksolid Custom Elements wird dynamisch per JavaScript das Feld "selector" in der TinyMCE Config ersetzt.

Die Config ist vorher durch den TinyMcePluginLoader modifiert worden ... es entsteht aber ein valide Konfiguration.

Aus einem unerklärlichen Grund findet das JavaScript von Rocksolid Custom Elements diesen Feld in der TinyMCE Config dann nicht mehr.

Das Problem liegt also m.E. in der Erweiterung Rocksolid Custom Elements und müsste somit von @madeyourday weiter untersucht werden.

**Comment by jenda77** [comment]
Vielen Dank für die Info. Ich schicke es dann an den Rocksolid-Service. 

Liebe Grüße,

Jan

**Comment by ausi** [comment]
> Auf Seiten der Rocksolid Custom Elements wird dynamisch per JavaScript das Feld "selector" in der TinyMCE Config ersetzt.

Diesen Punkt kann ich nicht ganz nachvollziehen, ich habe keine Stelle gefunden an der die Custom Elements in den `selector` eingreifen.

Ich denke das Problem liegt daran, dass der TinyMcePluginLoader nicht mehrere TinyMCE-Felder in einer Ansicht unterstützt. Man kann das relativ einfach testen indem man folgenden Code in die *dcaconfig.php* einträgt:

```php
$GLOBALS['TL_DCA']['tl_content']['fields']['text2'] =
	$GLOBALS['TL_DCA']['tl_content']['fields']['text'];
$GLOBALS['TL_DCA']['tl_content']['palettes']['text'] = str_replace(
	',text;',
	',text,text2;',
	$GLOBALS['TL_DCA']['tl_content']['palettes']['text']
);
```

Wenn man danach ein Text-Inhaltselement anlegt oder editiert sieht man, dass es ohne den TinyMcePluginLoader funktioniert, mit dem TinyMcePluginLoader erhält das zweite Feld jedoch keinen TinyMCE.

In [TinyMcePluginLoader.php:83](https://github.com/cliffparnitzky/TinyMcePluginLoader/blob/7b834d9c580465b6a32b74349be8c9bb9870b00d/system/modules/TinyMcePluginLoader/classes/TinyMcePluginLoader.php#L83) werden alle TinyMCE Konfigurationen mit der angepassten Konfiguration des ersten Elements ersetzt. Dadurch wird aus den zuvor unterschiedlichen Einträgen `selector: "#ctrl_text"` und `selector: "#ctrl_text2"` derselbe Eintrag `selector: "#ctrl_text"` wodurch das Textfeld `ctrl_text2` keinen TinyMCE Editor erhält.

**Comment by cliffparnitzky** [comment]
So ein mist, so weit hab ich gar nicht gedacht. Ja, das macht Sinn. Danke @ausi , dann würde ich sagen, dass ihr die Tickets bei euch schließt und ich mich dem selector Problem mal widme.

**Comment by cliffparnitzky** [comment]
Fixed with #7
