### ISSUE TITLE
Closing SCRIPT gets not rendered with newline LF before itself

### ISSUE THREAD

**Issue by Aybee** [cliffparnitzky/TinyMcePluginLoader#8]
Wenn in der tinyMCE.php (tinyCustom.php) eine Leerzeile vor dem schließenden SCRIPT kommt, wird dieses `</script>` nicht mehr gerendert. Dadurch funktioniert der RTE im Backend nicht mehr.
```php
// tinyCustom.php
// ...
});

</script>
<?php endif; ?>
```
Das passiert nur mit newlines LF (UNIX, default). Mit CR+LF (DOS) oder CR (MAC) ist alles ok.

**Comment by cliffparnitzky** [comment]
Hmm, denke mal, dass es am `\n` im Regex liegt: https://github.com/cliffparnitzky/TinyMcePluginLoader/blob/master/system/modules/TinyMcePluginLoader/classes/TinyMcePluginLoader.php#L44

Muss muss testweise entfernt werden, ob das überhaupt nötig ist.

**Comment by Aybee** [comment]
Ich denke es ist nötig, da ja viele mit tinyCustom arbeiten.

Arbeitest du daran, oder soll ich mal gucken, ob ich es hinbekomme?

**Comment by cliffparnitzky** [comment]
Im Grunde soll `tinyCustom` ja nicht nötig sein, wenn man den PluginLoader benutzt ... das ist ja der Sinn dahin, eben keine PHP Dateien modifizieren zu müssen.

Nichtsdestotrotz kann man den Regex (wenn möglich) überarbeiten. Du kannst das gern ausprobieren. Ich komme sicher nicht in den kommenden Tagen dazu.

**Comment by Aybee** [comment]
Das war ja easy
```php
private static $TINY_LOADER_REGEX = "/<script>\nwindow.tinymce && tinymce.init\(\{.*\}\);\n\r<\/script>/Us";
```
getestet mit allen drei Varianten.

> Im Grunde soll tinyCustom ja nicht nötig sein

Ich z.B. möchte nicht auf meine Modifikationen verzichten, die ich mir mit Mühe erarbeitet habe und ich weiß nicht, ob ich die mit deinen Plugins abgedeckt bekomme. Dann die ein oder andere Funktion über deine Plugins reinholen zu können wäre schon klasse.

**Comment by cliffparnitzky** [comment]
Ganz am Anfang des Regex steht auch noch ein `\n`. Sollte der auch durch `\r` ergänzt werden?

> Ich z.B. möchte nicht auf meine Modifikationen verzichten, die ich mir mit Mühe erarbeitet habe und ich weiß nicht, ob ich die mit deinen Plugins abgedeckt bekomme. Dann die ein oder andere Funktion über deine Plugins reinholen zu können wäre schon klasse.

Ja, deine Modifikationen kannst du dann am besten ein ein eigenes Package packen ... Toolsbars definieren, etc. und dann immer alles auf einen Schlag per Composer installieren. Kann ich dir an anderer Stelle mal erklären. Oder ich stelle mal ein Beispiel zusammen.

**Comment by Aybee** [comment]
> Ganz am Anfang des Regex steht auch noch ein \n. Sollte der auch durch \r ergänzt werden?

Ich habe versucht durch newlines an anderen Stellen in der tinyCustom Fehler zu provozieren, ist mir aber nicht gelungen. Also kann der wohl so bleiben.

Vielleicht kann ich dir in einem Gespräch, evtl. über Skype mal erklären was ich gemacht habe. Ist nicht viel, habe auch keine Plugins reingebracht, habe nur das was vom Core schon da ist sinnvoll konfiguriert, sodass die Sachen wieder benutzbar sind, so wie früher.

**Comment by cliffparnitzky** [comment]
Ich hab das nun in meinem Testsystem mal ausprobiert und bin leider nicht erfolgreich gewesen. Die Sache ist, dass genau der Teil der Config wesentlich dafür ist, um den String zu zerlegen und nachher wieder zusammenbauen zu können. Der Regex erwartet am Ende `});\n<\/script>`. Dies wird zerlegt am `\n` und somit erhält man 2 Chunks. Wenn dort nun aber eine weitere Zeile drin ist, bekommt man 3 Chunks, usw. .

Da die Contao Default Schreibweise keine Leerzeile drin hat, habe ich mich daran gehalten.

@Aybee Es wäre also am besten wenn du diese Zeile einfach bei dir entfernst.

Den Teil, dass die Newline Character unschiedlich sein müssen, habe ich in #9 verschoben.

**Comment by cliffparnitzky** [comment]
Okay, geht doch mit wenig Aufwand. Ist aber lediglich die Möglichkeit zwischen `<script>` und Tiny Config 1-n Newlines zu haben.

@Aybee Bitte teste mal den aktuellen Master bei dir. Auch bzgl. dem Fix in #9 .

**Comment by Aybee** [comment]
Sorry, hatte heute keine Zeit.

Das mit dem **\r** kannste vergessen, ich hatte mich nur auf den Fehler im BE konzentriert und gar nicht beachtet, dass dadurch die Zusätze nicht geladen wurden.

Ich habe eine regex gefunden, welche die Scripte findet auch wenn noch Zeilen davor oder dahinter kommen.
`"/<script>\s*window\.tinymce && tinymce\.init.*<\/script>/Us"`

Aber nachdem ich mal angefangen habe mich ein wenig in den Code einzulesen ist mir klar geworden, dass das alles irgendwie keinen Sinn macht. So wie du es programmiert hast muss man aufpassen, dass die tinyCustom noch eine gewisse Form wahrt.

Eigentlich wäre es sauberer, wenn man das tinymce.init-Object nur suchen und dann per JS erweitern bzw. ändern würde. Ich weiß aber nicht wie das geht. Ich weiß bis jetzt auch zu wenig über die Plugins, was damit alles angestellt werden kann. Ob z.B. "nur" weiter Object-Items hinzugefügt werden können wie z.B. 
`importcss_append: true,`

**Comment by cliffparnitzky** [comment]
Ja gut, mit `\s` findet man mehr Metacharacter ... das kann man sicher auch machen.

So wie es programmiert ist, gehe ich davon aus, dass man keine eigene Config hat, weil (wie oben schon erwähnt) dann alles per eigenem Package gemacht werden soll. Der Sinn ist: bei Installation eines Systems für Tiny Konfiguration keine PHP Dateien ändern zu müssen. Hat man doch eigene Config Dateien, kann man sich den PluginLoader sparen.

Das tinymce.init-Object zu suchen und mittels JavaScript zu erweitern ist auch ein Ansatz, die Config zu ändern ... imho aber nicht besser und nicht schlechter, nur anders.

Die vorhanden Plugins sind nicht von mir geschrieben ... Es werden lediglich Pakete geschnürt um sie einzubinden. Mal ein komplettes Plugin (fontawesome), mal nur um z.B. nen Button in die Toolbar zu packen.

Weitere Info zum "Was und Warum" gibt es hier: http://ck2015.contao.cliff-parnitzky.de/

**Comment by Aybee** [comment]
Ok, danke für die Antwort. Gut, dass ich diese Erweiterung jetzt kenne. Gut gemacht, diese Was und Warum Seite, danke. Wäre schön, wenn da alle Plugins vorgestellt würden.

**Comment by cliffparnitzky** [comment]
Das ist mein Vortrag von der Contao Konferenz 2015 - da kann man nicht mehr viel ändern.

Die Plugins sind alle hier gelistet: https://github.com/cliffparnitzky/TinyMcePluginLoader#plugins (inkl. Kompatibilität und Link zu Detailinformationen.)
